# Generated by Django 5.2.5 on 2025-09-05 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='condominios_permitidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='condominio.condominio'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moradores', to='condominio.unidade'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='bloco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominio.bloco'),
        ),
        migrations.AlterUniqueTogether(
            name='unidade',
            unique_together={('bloco', 'numero')},
        ),
    ]
