# Generated by Django 5.2.5 on 2025-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_condominio_usuarios_alter_bloco_condominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='sf_property_id',
            field=models.CharField(blank=True, max_length=18, verbose_name='Salesforce Property Id'),
        ),
    ]
