# Generated by Django 5.2.5 on 2025-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0003_condominio_sf_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='sf_contact_id',
            field=models.CharField(blank=True, max_length=18, verbose_name='Salesforce Contact Id'),
        ),
    ]
