# Generated by Django 5.2.5 on 2025-09-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0004_morador_sf_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='sf_property_id',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='Salesforce Property Id'),
        ),
    ]
