# Generated by Django 5.2.5 on 2025-09-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0005_alter_condominio_sf_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='sf_unidade_id',
            field=models.CharField(blank=True, default='', max_length=18, verbose_name='Salesforce Property Id'),
        ),
    ]
