# Generated by Django 5.2.5 on 2025-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_unidade_sf_unidade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='sf_opportunity_id',
            field=models.CharField(blank=True, max_length=18, verbose_name='Salesforce Opportunity Id'),
        ),
    ]
