# Generated by Django 5.2.5 on 2025-10-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0007_morador_sf_opportunity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
