# Generated by Django 5.2.5 on 2025-11-06 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0008_alter_morador_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bicicletas', to='condominio.bloco')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bicicletas', to='condominio.unidade')),
            ],
        ),
    ]
