# Generated by Django 5.2.5 on 2025-11-06 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0009_bicicleta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='blocos_permitidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
