# Generated by Django 5.2.5 on 2026-01-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0010_bloco_usuarios_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='boleto_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='face_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_moradores/'),
        ),
    ]
