# Generated by Django 5.2.5 on 2025-08-26 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transportadora', models.CharField(blank=True, max_length=120)),
                ('codigo_rastreamento', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('ENTREGUE', 'Entregue ao Morador'), ('DEVOLVIDA', 'Devolvida ao Remetente')], default='RECEBIDA', max_length=12)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='encomendas/fotos/')),
                ('assinatura_entrega', models.ImageField(blank=True, upload_to='encomendas/assinaturas/')),
                ('observacoes', models.TextField(blank=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.morador')),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomendas_entregues', to=settings.AUTH_USER_MODEL)),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomendas_recebidas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pessoa_tipo', models.CharField(choices=[('MORADOR', 'Morador'), ('VISITANTE', 'Visitante'), ('PRESTADOR', 'Prestador'), ('ENTREGADOR', 'Entregador')], max_length=12)),
                ('pessoa_nome', models.CharField(max_length=120)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('metodo', models.CharField(choices=[('TAG', 'TAG/Cartão'), ('QR', 'QR Code'), ('BIO', 'Biometria'), ('PWD', 'Senha')], max_length=3)),
                ('resultado', models.CharField(choices=[('OK', 'Permitido'), ('NO', 'Negado')], max_length=2)),
                ('motivo_negado', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.unidade')),
            ],
        ),
    ]
