# Generated by Django 5.2.5 on 2025-08-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomenda',
            options={'permissions': [('pode_entregar_encomenda', 'Pode entregar/baixar encomenda'), ('pode_receber_encomenda', 'Pode receber/registrar chegada de encomenda')]},
        ),
    ]
