# Generated by Django 5.2.5 on 2025-09-04 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
        ('portaria', '0002_alter_encomenda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(max_length=32, unique=True)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('documento', models.CharField(blank=True, max_length=50)),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condominio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.condominio')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.unidade')),
            ],
            options={
                'ordering': ['-created_date', '-imported_at'],
                'indexes': [models.Index(fields=['created_date'], name='portaria_vi_created_bc48a1_idx'), models.Index(fields=['nome'], name='portaria_vi_nome_a5433a_idx')],
            },
        ),
    ]
