# Generated by Django 5.2.5 on 2025-09-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0003_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='etiqueta_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='labels/'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='salesforce_ticket_id',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
