# Generated by Django 5.2.5 on 2025-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0004_encomenda_etiqueta_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParametroNome', models.CharField(max_length=100, unique=True)),
                ('ParametroValor', models.CharField(max_length=200)),
            ],
        ),
    ]
