# Generated by Django 5.2.5 on 2025-09-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0005_parametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacesso',
            name='resultado',
            field=models.CharField(choices=[('OK', 'Permitido'), ('NO', 'Negado'), ('AG', 'Aguardando liberação')], max_length=2),
        ),
    ]
