# Generated by Django 5.2.5 on 2025-09-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0006_unidade_sf_unidade_id'),
        ('portaria', '0006_alter_eventoacesso_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='sf_visitor_log_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('cor', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condominio.condominio')),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.morador')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.unidade')),
            ],
            options={
                'permissions': [('pode_gerenciar_veiculos', 'Pode gerenciar veículos cadastrados')],
            },
        ),
    ]
