# Generated by Django 5.2.5 on 2025-09-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0007_visitorlog_sf_visitor_log_id_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='PackageName',
            field=models.CharField(blank=True, choices=[('iFood', 'iFood'), ('Amazon', 'Amazon'), ('Mercado Livre', 'Mercado Livre'), ('Correios', 'Correios'), ('Outros', 'Outros')], max_length=20),
        ),
    ]
