# Generated by Django 5.2.5 on 2025-10-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0008_encomenda_packagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacesso',
            name='sf_visitor_log_id',
            field=models.CharField(blank=True, max_length=18, verbose_name='Salesforce VisitorLog Id'),
        ),
    ]
