# Generated by Django 5.2.5 on 2025-10-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0009_eventoacesso_sf_visitor_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoacesso',
            name='metodo',
        ),
    ]
