# Generated by Django 5.2.5 on 2025-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0010_remove_eventoacesso_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacesso',
            name='pessoa_telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
