# Generated by Django 5.2.5 on 2025-10-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0007_morador_sf_opportunity_id'),
        ('portaria', '0011_eventoacesso_pessoa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacesso',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='condominio.morador'),
        ),
    ]
