# Generated by Django 5.2.5 on 2025-10-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0012_eventoacesso_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacesso',
            name='liberado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
