# Generated by Django 5.2.5 on 2025-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0013_eventoacesso_liberado_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacesso',
            name='resultado',
            field=models.CharField(choices=[('Permitted', 'Permitted'), ('Cancelled', 'Cancelled'), ('Requested', 'Requested'), ('CheckIn', 'CheckIn')], max_length=15),
        ),
    ]
