# Generated by Django 5.2.5 on 2025-10-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0014_alter_eventoacesso_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoacesso',
            name='pessoa_tipo',
            field=models.CharField(choices=[('Familia', 'Familia'), ('Amigos', 'Amigos'), ('Prestador de serviço', 'Prestador de serviço')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventoacesso',
            name='resultado',
            field=models.CharField(choices=[('Permitted', 'Permitido'), ('Cancelled', 'Negado'), ('Requested', 'Aguardando'), ('CheckIn', 'CheckIn')], max_length=15),
        ),
    ]
