# Generated by Django 5.2.5 on 2025-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0015_alter_eventoacesso_pessoa_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacesso',
            name='data_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventoacesso',
            name='pessoa_tipo',
            field=models.CharField(choices=[('Family', 'Familia'), ('Friends', 'Amigos'), ('Service', 'Prestador de serviço')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventoacesso',
            name='resultado',
            field=models.CharField(choices=[('Permitted', 'Permitido'), ('Cancelled', 'Negado'), ('Requested', 'Aguardando'), ('Checked In', 'Liberado')], max_length=15),
        ),
    ]
