# Generated by Django 5.2.5 on 2025-10-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0016_eventoacesso_data_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='SenhaRetirada',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='PackageName',
            field=models.CharField(blank=True, choices=[('iFood', 'iFood'), ('Amazon', 'Amazon'), ('Mercado Livre', 'Mercado Livre'), ('Correios', 'Correios'), ('Loggi', 'Loggi'), ('Outros', 'Outros')], max_length=20),
        ),
    ]
