# Generated by Django 5.2.5 on 2025-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0017_encomenda_senharetirada_alter_encomenda_packagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='arquivo_01',
            field=models.FileField(blank=True, upload_to='encomendas/arquivos/'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='arquivo_02',
            field=models.FileField(blank=True, upload_to='encomendas/arquivos/'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='arquivo_03',
            field=models.FileField(blank=True, upload_to='encomendas/arquivos/'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='arquivo_04',
            field=models.FileField(blank=True, upload_to='encomendas/arquivos/'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='arquivo_05',
            field=models.FileField(blank=True, upload_to='encomendas/arquivos/'),
        ),
    ]
