# Generated by Django 5.2.5 on 2025-10-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0018_encomenda_arquivo_01_encomenda_arquivo_02_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='RetiradoPor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
