# Generated by Django 5.2.5 on 2025-10-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0019_encomenda_retiradopor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomenda',
            name='RetiradoPor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='SenhaRetirada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
