# Generated by Django 5.2.5 on 2026-01-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0020_alter_encomenda_retiradopor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tentativas', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('integrado_em', models.DateTimeField(blank=True, null=True)),
                ('Encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.encomenda')),
            ],
        ),
    ]
