# Generated by Django 5.2.5 on 2026-01-21 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0021_filaintegracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filaintegracao',
            name='Encomenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_integracao', to='portaria.encomenda'),
        ),
        migrations.AlterUniqueTogether(
            name='filaintegracao',
            unique_together={('Encomenda',)},
        ),
    ]
